server:
  port: 8081

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/joaquinmatias99/microservicioshotels-cities.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}

